### ISSUE TITLE
]cider.version fails with a value error if Expose->Root properties is not ticked in Dyalog

### ISSUE THREAD

**Issue by dyavc** [aplteam/Cider#1]
]cider.version fails with a value error if Expose->Root properties is not ticked in Dyalog

]cider.version
* Command Execution Failed: VALUE ERROR

      ]cider.version
  Cider  0.4.0+109  2021-10-13    

Try to get the aplversion this way instead:  
'.' ⎕wg 'aplversion'

**Comment by aplteam** [comment]
Fixed in 0.4.1

**Comment by mbaas2** [comment]
This issue has come back and it also affects `CreateProject`  (and possibly others that I didn't try)

**Comment by aplteam** [comment]
Cannot reproduce. Which version of Cider are you using?

Please switch on `debug` and send over the precise error message.
