### ISSUE TITLE
Feature request: unbox user command output option

### ISSUE THREAD

**Issue by rikedyp** [aplteam/Cider#13]
It would be nice if there was a way to have user command output no boxed since I usually have ` ]box on -fns=on`

**Comment by aplteam** [comment]
Well, you get what you are asking for with `]box on -fns=on`!

The function `]Cider.ListAlias` for example returns a matrix with two columns (alias and path) and as many lines as there are alises defined. That is certainly not bad.

To me this looks more like a problem of the user command framework than a Cider problem.

The framework knows whether a result is assigned or just printed to the session. If it is printed to the session it could do

```
1↓∊(⎕ucs 13),¨↓⎕FMT 
```

on the result in case that is a matrix, but it could keep returning the matrix when the result is assigned.

Wouldn't that be better?
