### ISSUE TITLE
CreateProject usercommand should create it in current dir if folder specified as `.`

### ISSUE THREAD

**Issue by e9gille** [aplteam/Cider#14]
With the command:
```
      ]cider.createProject . MyProject
```

I expect the project to be created in the current dir, instead it is created in the parent folder.
Perhaps change the line below to:
```
          folder←⊃1 ⎕NPARTS './'
```
https://github.com/aplteam/Cider/blob/35552f8a31da371172e4106535ac93c29ab5ea84/APLSource/Cider_uc.dyalog#L530

**Comment by aplteam** [comment]
Fixed in 0.21.2
