### ISSUE TITLE
dyadic init function errors on OpenProject

### ISSUE THREAD

**Issue by rikedyp** [aplteam/Cider#32]
I created a dyadic, non-result-returning init function:
```
      ⎕VR'APLAutoHotKey.DevSetup'
     ∇ dir DevSetup config
[1]    LoadHTML dir
[2]    LoadKeymaps dir
[3]    LoadSnippets dir
     ∇
```

According to the docs:
> Such a function may be niladic, monadic, ambivalent or dyadic:
>    - A non-niladic function receives a namespace with the project configuration as right argument
>    - An ambivalent or dyadic function receives a path as left argument: this is the home folder of the project

Instead, I got an error:
```
 Executing the project's initialising function "DevSetup"... 
 ┌───────────────────────────────────────┐ 
 │Invalid function valence: is ambivalent│ 
 └───────────────────────────────────────┘ 
```

**Comment by aplteam** [comment]
Actually, the bug is the documentation. The directory is available as `CiderConfig.HOME` in any case, so there is no need to waste the left argument on this.

I would rather keep the option open to pass something more useful via `⍺` at a later stage, wouldn't you agree?

**Comment by aplteam** [comment]
The message is wrong as well: should be:

"Invalid function valence: is dyadic"
