### ISSUE TITLE
Value Error in AddAlias

### ISSUE THREAD

**Issue by mkromberg** [aplteam/Cider#37]
If you provide an invalid folder name, AddAlias hits a value error on "p" trying to display the error message:

      ⎕SE.Cider.AddAlias 'clocks' 'c:\tmp\clockproj' ⍝ Reverse argument order
VALUE ERROR: Undefined name: p
AddAlias[16] (1 parms.batch)p'Could not find "',folder,'"'
                            ∧
                            
      ]cider.version
0.35.0+410

**Comment by aplteam** [comment]
Fixed in 0.36.0
