### ISSUE TITLE
Confusing Prompt from AddTatinDependencies

### ISSUE THREAD

**Issue by mkromberg** [aplteam/Cider#47]
The question should make it clear that the question is about which of my open projects to add vikings to. For example:

"Which open project should vikings be added to?"

---

Currently:

      ]cider.addTatinDependencies vikings
--- Select a Cider project: ----------
   1.  #.vikings  c:/tmp/vikings  
   2.  #.christ   c:/tmp/christ   

Also, after asking this, the subsequent question

"christ: add dependencies to tatin-dependencies/ ? (Y/n)"

... seems unnecessary ...

**Comment by aplteam** [comment]
Fixed in 0.40.0
