### ISSUE TITLE
Avoid version clashes in NuGet test cases

### ISSUE THREAD

**Issue by Alexander-Block** [aplteam/Cider#68]
As described in PR #67 it seems that it is currently not possible to load two different versions of the same NuGet dependency in one test run. This led to a problem (which will occur again at some point in the future) with `Test_NuGet_002` and `Test_NuGet_010`. The former uses the current version for `NodaTime`, while the latter uses a fixed version.

I propose that we should rework all NuGet test cases to use fixed (and equal) versions of all NuGet dependencies used to avoid our test run unexpectedly breaking when a new version of some dependency gets released to NuGet.

**Comment by aplteam** [comment]
Tests are now executed in an independent process, fixing the problem.
