### ISSUE TITLE
Update Dyalog-NuGet package?

### ISSUE THREAD

**Issue by Bombardier-C-Kram** [aplteam/Cider#78]
When loading the newest release of Cider in dyalog, an error message seems to appear. I believe that this is fixed in dyalog-NuGet-0.2.2. 

*** Establishing variable </home/spacequacker/dyalog.190U64.files/StartupSessio
      n/CiderTatin/../../SessionExtensions/CiderTatin/Cider/dyalog-NuGet-0.2.1/
      NuGet/тОХIO.apla> failed with EstablishVariablesFromFiles[12] тОХIO←⍵; RC
      =2
*** Establishing variable </home/spacequacker/dyalog.190U64.files/StartupSessio
      n/CiderTatin/../../SessionExtensions/CiderTatin/Cider/dyalog-NuGet-0.2.1/
      NuGet/тОХML.apla> failed with EstablishVariablesFromFiles[12] тОХML←⍵; RC
      =2

**Comment by aplteam** [comment]
Are you sure you are using the latest version? Cider uses version 0.2.1 of Dyalog's NuGet package for a while now.

**Comment by Bombardier-C-Kram** [comment]
https://github.com/Dyalog/nuget/blob/main/APLSource%2Fapl-package.json

Seems like Dyalog needs to update the package on Tatin.dev, then?

**Comment by aplteam** [comment]
You are right! I was under the impression that 0.2.1 fixed the problem, but that is not correct: for that, we need 0.2.2, which has not been published yet.
